// File generated by rpc compiler. Do not edit.

package org.commoncrawl.query;

import java.io.DataInput;
import java.io.DataOutput;
import java.util.BitSet;
import java.io.IOException;
import org.apache.hadoop.io.Writable;
import org.apache.hadoop.io.WritableComparable;
import org.apache.hadoop.record.Buffer;
import org.commoncrawl.util.shared.FlexBuffer;
import org.commoncrawl.util.shared.TextBytes;
import org.commoncrawl.util.shared.MurmurHash;
import org.commoncrawl.util.shared.ImmutableBuffer;
import org.commoncrawl.rpc.BinaryProtocol;
import org.apache.hadoop.util.ReflectionUtils;
import org.apache.hadoop.conf.Configuration;

// Generated File: QueryInputSplit
public class QueryInputSplit extends org.commoncrawl.rpc.RPCStruct<QueryInputSplit> implements WritableComparable {

	// optimized constructor helper 
	public static QueryInputSplit newInstance(Configuration conf) {
		return ReflectionUtils.newInstance(QueryInputSplit.class, conf);
	}

	// Writable Implementation
	public void write(DataOutput out) throws IOException {
		this.serialize(out, new BinaryProtocol());
	}

	public void readFields(DataInput in) throws IOException {
		this.deserialize(in, new BinaryProtocol());
	}

	// Comparable Implementation
	public int compareTo(Object other) {
		int result = ((Integer) shardId).compareTo((Integer) ((org.commoncrawl.query.QueryInputSplit) other).shardId);
		return result;
	}

	// getKey Implementation
	public String getKey() {
		return ((Integer) shardId).toString();
	}

	// Field Constants
	public static final int Field_SHARDID = 1;
	static final int FieldID_MAX = Field_SHARDID;

	// Field Declarations
	private BitSet __validFields = new BitSet(FieldID_MAX + 1);

	private int shardId;

	// Default Constructor
	public QueryInputSplit() {
	}

	// Accessors

	public final boolean isFieldDirty(int fieldId) {
		return __validFields.get(fieldId);
	}

	public final QueryInputSplit setFieldDirty(int fieldId) {
		__validFields.set(fieldId);
		return this;
	}

	public final QueryInputSplit setFieldClean(int fieldId) {
		__validFields.clear(fieldId);
		return this;
	}

	public int getShardId() {
		return shardId;
	}

	public QueryInputSplit setShardId(int shardId) {
		__validFields.set(Field_SHARDID);
		this.shardId = shardId;
		return this;
	}

	// Object Dirty support 

	public final boolean isObjectDirty() {
		boolean isDirty = !__validFields.isEmpty();
		return isDirty;
	}

	// serialize implementation 
	public final void serialize(DataOutput output, BinaryProtocol encoder) throws java.io.IOException {
		encoder.beginFields(output);
		// serialize field:shardId
		if (__validFields.get(Field_SHARDID)) {
			encoder.beginField(output, "shardId", Field_SHARDID);
			encoder.writeInt(output, shardId);
		}
		encoder.endFields(output);
	}

	// deserialize implementation 
	public final void deserialize(DataInput input, BinaryProtocol decoder) throws java.io.IOException {
		// clear existing data first  
		clear();

		// reset protocol object to unknown field id enconding mode (for compatibility)
		decoder.pushFieldIdEncodingMode(BinaryProtocol.FIELD_ID_ENCODING_MODE_UNKNOWN);
		// keep reading fields until terminator (-1) is located 
		int fieldId;
		while ((fieldId = decoder.readFieldId(input)) != -1) {
			switch (fieldId) {
			case Field_SHARDID: {
				__validFields.set(Field_SHARDID);
				shardId = decoder.readInt(input);
			}
				break;
			}
		}
		// pop extra encoding mode off of stack 
		decoder.popFieldIdEncodingMode();
	}

	// clear implementation 
	public final void clear() {
		__validFields.clear();
		shardId = 0;
	}

	// equals implementation 
	public final boolean equals(final Object peer_) {
		if (!(peer_ instanceof QueryInputSplit)) {
			return false;
		}
		if (peer_ == this) {
			return true;
		}
		QueryInputSplit peer = (QueryInputSplit) peer_;
		boolean ret = __validFields.equals(peer.__validFields);
		if (!ret)
			return ret;
		if (__validFields.get(Field_SHARDID)) {
			ret = (shardId == peer.shardId);
			if (!ret)
				return ret;
		}
		return ret;
	}

	// clone implementation 
	@SuppressWarnings("unchecked")
	public final Object clone() throws CloneNotSupportedException {
		QueryInputSplit other = new QueryInputSplit();
		other.__validFields.or(this.__validFields);
		if (__validFields.get(Field_SHARDID)) {
			other.shardId = this.shardId;
		}
		return other;
	}

	// merge implementation 
	@SuppressWarnings("unchecked")
	public final void merge(QueryInputSplit peer) throws CloneNotSupportedException {
		__validFields.or(peer.__validFields);
		if (peer.__validFields.get(Field_SHARDID)) {
			this.shardId = peer.shardId;
		}
	}

	// hashCode implementation 
	public final int hashCode() {
		int result = 1;
		result = MurmurHash.hashInt((int) shardId, result);
		return result;
	}
}
